services:
  - type: web
    name: DarkLnes-app
    env: python
    buildCommand: |
      rm -rf .venv
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
