services:
  - type: web
    name: darklens-app
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
